name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up list
      id: create-list
      run: echo ##[set-output name=list;]foo,bar,baz
    - name: Set up string
      id: create-string
      run: echo ##[set-output name=string;]"foo,bar,baz"
  do-stuff:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ["en-US", "es-ES"]
    steps:
     - uses: actions/checkout@v1
     - name: Echo String
       run: echo ${{ steps.create-string.outputs.string }}
     - name: Echo Array
       run: echo ${{ steps.create-list.outputs.list }}

