name: CI

on: [push]
env:
  LANGS: "[nl-NL, fr-FR]"
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ${{ LANGS }}
    steps:
     - uses: actions/checkout@v1
     - name: Echo String
       run: echo ${{ steps.create-string.outputs.string }}
     - name: Echo Array
       run: echo ${{ steps.create-list.outputs.list }}

