name: Upload

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:

    - name: Install AWS CLI
      run: brew install awscli && brew link awscli
    - name: Verify AWS CLI
      run: which awscli
